version: '1.0'
name: pipeline-20240827
displayName: geeker-admin-js部署流水线
triggers:
  trigger: manual
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-3ed5489f
    displayName: 传输阶段
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: 连接并构建
        hostGroupID:
          ID: tx
          hostID:
            - 63ee3d30-3ff5-4fd2-b10d-c9bca8bc9282
        script:
          - '# 请在此输入您想执行的脚本'
          - cd /www/wwwroot/geeker-admin-js/geeker-admin-js
          - rm -rf ./dist
          - npm install
          - npm run build:pro
          - cp ./dist/* ../dist/
          - ''
        notify: []
        strategy:
          retry: '0'
